name: dart_reed_solomon_nullsafety
description: Reed–Solomon error correction. Forked from dart_reed_solomon to add sound null safety.
version: 0.2.0
homepage: https://github.com/AulosRafael/reed_solomon

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.20.1
