name: dart_reed_solomon
description: Reed–Solomon error correction
version: 0.1.0+2
homepage: https://github.com/AulosRafael/reed_solomon

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.20.1
