name: reed_solomon
description: Reed–Solomon error correction
version: 0.0.1
author: Aulos Rafael
homepage: https://github.com/AulosRafael/reed_solomon

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
