name: reed_solomon
description: Reed–Solomon error correction
version: 0.0.1
homepage: https://github.com/AulosRafael/reed_solomon

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  test:
